version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "update-dependencies"
    open-pull-requests-limit: 10
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "update-dependencies"
    open-pull-requests-limit: 10
