name: Build project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        distribution: [ 'temurin' ]
        node-version: [ 16.x ]
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Maven tests
        run: mvn verify

      - name: Run tests
        run: npm test
